name: Run compute_daily script

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 12 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
        
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4

      - name: execute compute_daily script
        run: python ${GITHUB_WORKSPACE}/scripts/metrostatus.py

      - name: commit and push changes
        run: |
          git config --global user.name 'enriquetecfan11'
          git config --global user.email 'enriquemondejar15@gmail.com'
          git add .
          git commit -m "Update daily status"
          git push
